---

- name: Ensure that the application file permissions are set properly
  file: path={{ project_path }}
        recurse=yes
        owner={{ user }}
        group={{ group }}
        state=directory
  notify: restart application
