---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: copy local_settings.py
  template: src=local_settings.py.j2 dest={{ application_path }}/{{ application_name }}/local_settings.py

- name: Run Django DB migrations
  django_manage:
    command: migrate
    app_path: "{{ application_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  when: run_django_db_migrations
  tags: django.migrate

- name: Run the Django loaddata command
  django_manage:
    command: loaddata
    app_path: "{{ application_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
    fixtures: "{{ django_initial_data }}"
  when: run_django_loaddata
  tags: django.loaddata

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ application_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  when: run_django_collectstatic
  tags: django.collectstatic
