---

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml

- include: copy_project_sources.yml

- include: setup_django_app.yml

- include: setup_supervisor.yml

- include: set_file_permissions.yml

- include: setup_nginx.yml
