---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: root
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
    - symlink_sources: yes
  vars_files:
    - env_vars/local.yml

  roles:
    - db
    - django_project
    - nginx
